spring:
  mvc:
    pathmatch:
      use-suffix-pattern: true

stremio:
  manifest:
    id: sample.stremio.addon
    name: HelloPlugin
    version: ${version}
    description: >-
      This is my plugin description.
      This is just a sample.
    logo: https://www.stremio.com/website/stremio-logo-small.png
    resources:
      - catalog
      - stream